cars = ['bmw', 'audi', 'toyata', 'honda', 'subalu']
print('Here is the original list:')
print(cars)
print('\nHere is the sorted list:')
print(sorted(cars))
print('\nHere is the original list again')
print(cars)
cars.sort()
print('\n')
print(cars)
cars.sort(reverse = True)
print('\n')
print(cars)
cars.reverse()
print(cars)
