FavoriteTravlePlaces = ["tibet","xi'an", "beijing", "california", "shenzhen"]
print(FavoriteTravlePlaces)
print(sorted(FavoriteTravlePlaces))
print(FavoriteTravlePlaces)
print(sorted(FavoriteTravlePlaces,reverse = True))
print(FavoriteTravlePlaces)
FavoriteTravlePlaces.reverse()
print(FavoriteTravlePlaces)
FavoriteTravlePlaces.reverse()
print(FavoriteTravlePlaces)
FavoriteTravlePlaces.sort()
print(FavoriteTravlePlaces)
FavoriteTravlePlaces.sort(reverse = True)
print(FavoriteTravlePlaces)